// @constants/sheetNames.ts
// The sheetnames list was generated using the logSheetNames function
// then cut and pasted here to avoid a runtime dependency.
// It should be updated whenever sheets are added or removed.
// The list is in alphabetical order.
// It includes hidden and system sheets.
// Last updated 2025-09-30
export const sheetNames = [
  "$Queue",
  "$QueueDead",
  "$Status",
  "Assets",
  "BMONZO",
  "Balance sheet",
  "Bank accounts",
  "Bank cards",
  "Bank credits due",
  "Bank debits due",
  "Bank interest",
  "Budget",
  "Budget FOUR weekly change",
  "Budget FOUR weekly transactions",
  "Budget ad hoc change",
  "Budget ad hoc transactions",
  "Budget annual change",
  "Budget annual transactions",
  "Budget breakdown",
  "Budget daily",
  "Budget monthly change",
  "Budget monthly transactions",
  "Budget predicted spend",
  "Budget transactions",
  "Budget weekly change",
  "Budget weekly transactions",
  "Categories",
  "Category clash",
  "Category clash data",
  "Category groups",
  "Check fixed amounts",
  "Config",
  "Dependencies",
  "Description replacements",
  "Gift recipients",
  "Gift tiers",
  "HMRC B",
  "HMRC Queries",
  "HMRC S",
  "HMRC S NIC record",
  "HMRC businesses",
  "HMRC categories",
  "HMRC constant amounts by year",
  "HMRC constant percentages by year",
  "HMRC constants by year",
  "HMRC fields",
  "HMRC income stream types",
  "HMRC income streams",
  "HMRC overrides by year",
  "HMRC pensions",
  "HMRC people details",
  "HMRC property",
  "HMRC questions",
  "HMRC questions 2022 to 2023",
  "HMRC questions 2023 to 2024",
  "HMRC questions 2024 to 2025",
  "HMRC self-assessment",
  "HMRC tax years",
  "HMRC totals by bank",
  "HMRC totals by tax year and category",
  "HMRC transactions",
  "Imported data",
  "Income interest",
  "Income planning",
  "Income property",
  "Income self-employment",
  "Institutions",
  "Josh",
  "Liabilities",
  "Loan Adam Perry",
  "Loan Charlie Bernard",
  "Loan Glenburnie",
  "Loan Linda Hayman",
  "Loans",
  "Money owed by us",
  "Money owed to us",
  "My formulas",
  "My formulas examples",
  "Not in transaction categories",
  "Our money",
  "Our money history",
  "PMT",
  "Pension UK Gov",
  "Pensions",
  "People",
  "Property",
  "Property L1 3BH",
  "Property SW11 2TJ",
  "Property SW17 0SR",
  "Property SW18 3PT",
  "Queries",
  "Query lookup",
  "Receipts",
  "Shares",
  "Spreadsheet summary",
  "Summary",
  "Transaction categories",
  "Transactions",
  "Transactions by category",
  "Transactions by category group",
  "Transactions by date",
  "Transactions by nett amount",
  "Uncategorised by date",
  "Unreconciled",
  "Weekday",
  "Xfers by date",
  "Xfers check",
  "Xfers mismatch",
  "Xfers totals",
  "Xfers totals by year",
  "_$SPLIT",
  "_AHALIF",
  "_BCHASE",
  "_BCHRND",
  "_BCHSAV",
  "_BCOISA",
  "_BCOLOY",
  "_BCYNER",
  "_BFAMIL",
  "_BGOLDM",
  "_BMETRO",
  "_BMOCHA",
  "_BMOFWN",
  "_BMOKID",
  "_BMONZO",
  "_BMOPAR",
  "_BMOSAV",
  "_BNSPBZ",
  "_BOAIS2",
  "_BOAISA",
  "_BOAKNO",
  "_BOXBUR",
  "_BPAYPA",
  "_BPOSTO",
  "_BSAISA",
  "_BSANTA",
  "_BSASA2",
  "_BSASA3",
  "_BSASAV",
  "_BSATAX",
  "_BTES01",
  "_BTESCO",
  "_BTRISA",
  "_BVANGA",
  "_BVMISA",
  "_BVMSAV",
  "_BWALLE",
  "_CLLOYD",
  "_CMETRO",
  "_CVITRA",
  "_GLOANA",
  "_JFIXES",
  "_JSANTA",
  "_JWALEU",
  "_SAMAZO",
  "_SCHASE",
  "_SCHBST",
  "_SCHRND",
  "_SCHSAV",
  "_SCOIS2",
  "_SCOISA",
  "_SCOLOY",
  "_SFAMIL",
  "_SGOLDM",
  "_SKROOO",
  "_SMETRO",
  "_SMOINX",
  "_SMONZ1",
  "_SMONZO",
  "_SMOPOT",
  "_SNSPBZ",
  "_SOAIS2",
  "_SOAISA",
  "_SOAKNO",
  "_SOXBUR",
  "_SPAYPA",
  "_SPOSTO",
  "_SREVOL",
  "_SSACR1",
  "_SSACRD",
  "_SSAISA",
  "_SSANT1",
  "_SSANTA",
  "_SSAPRM",
  "_SSAZ01",
  "_SSAZ02",
  "_SSAZ03",
  "_SSTARL",
  "_STAFIX",
  "_STASAV",
  "_STES01",
  "_STES02",
  "_STES03",
  "_STESCO",
  "_STRISA",
  "_SVANGA",
  "_SVI2TJ",
  "_SVI3BH",
  "_SVIIRF",
  "_SVMISA",
  "_SVMSAV",
  "_SWALLE",
  "_SZOPA1",
];
