// Auto-generated by extractGASFunctionsFromSrc.ts — do not edit manually

export const shimGlobals = [
  "applyDescriptionReplacements",
  "budget",
  "sendDailyEmail",
  "sortSheets",
] as const;

export type ExportedGlobal = (typeof shimGlobals)[number];