// Auto-generated by extractGASFunctionsFromSrc.ts — do not edit manually

export const shimGlobals = [
  "myScheduledTask",
  "onDateChange",
  "onEdit",
  "onOpen",
] as const;

export type ExportedGlobal = (typeof shimGlobals)[number];