// Auto-generated by extractGASFunctionsFromSrc.ts — do not edit manually

export const shimGlobals = [
  "applyDescriptionReplacements",
  "budget",
  "budgetAdHocTransactions",
  "categories",
  "dailySorts",
  "helloWorld",
  "mergeTransactions",
  "onOpen",
  "sendDailyEmail",
  "showAllAccounts",
  "sortSheets",
] as const;

export type ExportedGlobal = (typeof shimGlobals)[number];